name: aerostack_sdk
version: 0.1.0

description: A production-ready Flutter SDK for interacting with Aerostack API.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dio: ^5.0.0
  json_serializable: ^6.2.0

dev_dependencies:
  build_runner: ^2.3.3
  json_annotation: ^4.8.0